#!/usr/bin/env node
/**
 * generate.mjs — single-source generator for the ff-fab-marketplace.
 *
 * Source of truth:
 *   - .claude-plugin/marketplace.json            (registry; read by Claude Code + Copilot CLI)
 *   - plugins/<name>/.claude-plugin/plugin.json  (per-plugin manifest; version source of truth)
 *   - plugins/<name>/commands/*.md               (Claude slash commands)
 *   - plugins/<name>/agents/*.md                 (Claude agents)
 *
 * Generated mirrors (do not edit by hand):
 *   - .github/plugin/marketplace.json            (Copilot CLI primary path / VS Code)
 *   - plugins/<name>/.github/plugin.json         (Copilot CLI / VS Code manifest)
 *   - plugins/<name>/.github/prompts/*.prompt.md (VS Code prompt files, from commands/)
 *   - plugins/<name>/agents/<name>.agent.md      (Copilot agent naming, from agents/*.md)
 *
 * It also syncs each plugin's version/description into the marketplace registry.
 *
 * Usage:
 *   node scripts/generate.mjs           # write generated files + sync registry
 *   node scripts/generate.mjs --check   # fail (exit 1) if anything is out of sync
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync, statSync } from "node:fs";
import { dirname, join, basename, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

/** Collected (path -> desired content) outputs. */
const outputs = new Map();
const GENERATED_BANNER = "AUTO-GENERATED by scripts/generate.mjs — do not edit by hand.";

function json(obj) {
  return JSON.stringify(obj, null, 2) + "\n";
}

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function listDirs(path) {
  if (!existsSync(path)) return [];
  return readdirSync(path).filter((n) => statSync(join(path, n)).isDirectory());
}

function listFiles(path, ext) {
  if (!existsSync(path)) return [];
  return readdirSync(path).filter((n) => n.endsWith(ext) && statSync(join(path, n)).isFile());
}

function parseFrontmatter(md) {
  const m = md.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { fm: {}, body: md };
  const fm = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (kv) fm[kv[1]] = kv[2].trim();
  }
  return { fm, body: m[2] };
}

// --- Load canonical registry and sync per-plugin manifests into it ---
const marketplacePath = join(ROOT, ".claude-plugin", "marketplace.json");
const marketplace = readJson(marketplacePath);

if (!Array.isArray(marketplace.plugins)) {
  console.error(`${relative(ROOT, marketplacePath)}: "plugins" must be an array.`);
  process.exit(1);
}

for (const entry of marketplace.plugins) {
  const pluginDir = join(ROOT, entry.source.replace(/^\.\//, ""));
  const manifestPath = join(pluginDir, ".claude-plugin", "plugin.json");
  if (!existsSync(manifestPath)) {
    console.error(`Missing manifest: ${relative(ROOT, manifestPath)}`);
    process.exitCode = 1;
    continue;
  }
  const manifest = readJson(manifestPath);

  // Sync registry entry fields from the plugin manifest (manifest wins).
  entry.version = manifest.version;
  entry.description = manifest.description;
  if (manifest.author) entry.author = manifest.author;
  if (manifest.license) entry.license = manifest.license;
  if (manifest.category) entry.category = manifest.category;
  if (manifest.keywords) entry.keywords = manifest.keywords;

  // .github/plugin.json mirror.
  outputs.set(join(pluginDir, ".github", "plugin.json"), json(manifest));

  // VS Code prompt files from Claude commands.
  for (const cmd of listFiles(join(pluginDir, "commands"), ".md")) {
    const name = basename(cmd, ".md");
    const { fm, body } = parseFrontmatter(readFileSync(join(pluginDir, "commands", cmd), "utf8"));
    const desc = fm.description || `${name} command`;
    const prompt =
      `---\n` +
      `mode: agent\n` +
      `description: ${desc}\n` +
      `---\n` +
      `<!-- ${GENERATED_BANNER} Source: commands/${cmd} -->\n\n` +
      body.replace(/\$ARGUMENTS/g, "${input:arguments}").trimEnd() +
      "\n";
    outputs.set(join(pluginDir, ".github", "prompts", `${name}.prompt.md`), prompt);
  }

  // Copilot agent naming (.agent.md) from Claude agents (*.md, excluding *.agent.md).
  for (const agent of listFiles(join(pluginDir, "agents"), ".md")) {
    if (agent.endsWith(".agent.md")) continue;
    const name = basename(agent, ".md");
    outputs.set(
      join(pluginDir, "agents", `${name}.agent.md`),
      readFileSync(join(pluginDir, "agents", agent), "utf8")
    );
  }
}

// Registry: canonical (synced) + .github mirror.
outputs.set(marketplacePath, json(marketplace));
outputs.set(join(ROOT, ".github", "plugin", "marketplace.json"), json(marketplace));

// --- Apply or check ---
let drift = 0;
for (const [path, content] of outputs) {
  const current = existsSync(path) ? readFileSync(path, "utf8") : null;
  if (current === content) continue;
  drift++;
  if (CHECK) {
    console.error(`OUT OF SYNC: ${relative(ROOT, path)}`);
  } else {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, content);
    console.log(`wrote ${relative(ROOT, path)}`);
  }
}

if (CHECK && drift > 0) {
  console.error(`\n${drift} file(s) out of sync. Run: node scripts/generate.mjs`);
  process.exit(1);
}
if (!CHECK) console.log(drift === 0 ? "Already up to date." : `Updated ${drift} file(s).`);
